#!/bin/bash

export DEBUG=${DEBUG:-0}

export FLASK_ENV=${FLASK_ENV:-"production"}

export OCKLE_HOME=${OCKLE_HOME:-"/usr/lib/ockle"}
export OCKLE_LOG_DIR=${OCKLE_LOG_DIR:-"/var/log/ockle"}

export OCKLE_MYSQL_SERVER=${OCKLE_MYSQL_SERVER:-"localhost"}
export OCKLE_MYSQL_PORT=${OCKLE_MYSQL_PORT:-"3306"}
export OCKLE_MYSQL_USERNAME=${OCKLE_MYSQL_USERNAME:-"root"}
export OCKLE_MYSQL_PASSWORD=${OCKLE_MYSQL_PASSWORD:-"password"}
export OCKLE_DATABASE=${OCKLE_DATABASE:-"ockledb"}
export SQLALCHEMY_DATABASE_URI=mysql://${OCKLE_MYSQL_USERNAME}:${OCKLE_MYSQL_PASSWORD}@${OCKLE_MYSQL_SERVER}:${OCKLE_MYSQL_PORT}/${OCKLE_DATABASE}?charset=utf8

export OCKLE_WEBSERVER_ADDRESS=${OCKLE_WEBSERVER_ADDRESS:-"0.0.0.0"}
export OCKLE_WEBSERVER_PORT=${OCKLE_WEBSERVER_PORT:-"5180"}
export OCKLE_WORKERS=${OCKLE_WORKERS:-"5"}
export OCKLE_WEBSERVER_TIMEOUT=${OCKLE_WEBSERVER_TIMEOUT:-"60"}

export OCKLE_INSTANCE_LABEL_PREFIX=${OCKLE_INSTANCE_LABEL_PREFIX:-"transwarp.name"}
export OCKLE_INSTANCE_CONTROL_LABEL_PREFIX=${OCKLE_INSTANCE_CONTROL_LABEL_PREFIX:-"transwarp.install"}
export OCKLE_GUARDIAN_ENABLED=${OCKLE_GUARDIAN_ENABLED:-"false"}
export APP_GUARDIAN_ENABLED=${APP_GUARDIAN_ENABLED:-"true"}
export OCKLE_UPDATE_ENABLED=${OCKLE_UPDATE_ENABLED:-"true"}

export PRODUCT_META_HOME=${PRODUCT_META_HOME:-"/usr/lib/ockle/product-meta"}

export KUBERNETES_HOST=${KUBERNETES_HOST:-"http://localhost:8080"}
export KUBERNETES_CLIENT_CERT=${KUBERNETES_CLIENT_CERT:-""}
export KUBERNETES_CLIENT_KEY=${KUBERNETES_CLIENT_KEY:-""}
export KUBERNETES_CA=${KUBERNETES_CA:-""}
