version: '2'

services:

  catalog-database:
    image: 172.16.1.99/transwarp/mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - /opt/catalog/data:/var/lib/mysql
    ports:
      - "13306:3306"

  catalog-server:
    image: 172.16.1.99/gold/catalog:latest
    privileged: true
    restart: always
    command: bash /usr/lib/catalog/scripts/bootstrap.sh
    ports:
      - "4444:4444"
    environment:
      - FLASK_ENV=development
      - CATALOG_MYSQL_SERVER=catalog-db
      - CATALOG_MYSQL_USERNAME=root
      - CATALOG_MYSQL_PASSWORD=password
      - CATALOG_DATABASE=catalog_production
    depends_on:
      - catalog-database
    links:
      - catalog-database
