"""optimize field types

Revision ID: d6c6529db987
Revises: f06dcd57a55c
Create Date: 2018-01-21 17:46:03.285397

"""

# revision identifiers, used by Alembic.
revision = 'd6c6529db987'
down_revision = 'f06dcd57a55c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'data_quality',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('dataset', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('license', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('license', sa.Column('url', sa.String(length=1024), nullable=True))
    op.drop_index('title', table_name='license')
    op.create_unique_constraint(None, 'license', ['name'])
    op.drop_column('license', 'title')
    op.drop_column('license', 'web')
    op.add_column('reference', sa.Column('url', sa.String(length=1024), nullable=False))
    op.drop_column('reference', 'reference')
    op.add_column('source', sa.Column('url', sa.String(length=1024), nullable=False))
    op.drop_column('source', 'download_url')
    op.drop_column('source', 'access_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('access_url', mysql.VARCHAR(length=1024), nullable=False))
    op.add_column('source', sa.Column('download_url', mysql.VARCHAR(length=1024), nullable=False))
    op.drop_column('source', 'url')
    op.add_column('reference', sa.Column('reference', mysql.VARCHAR(length=1024), nullable=False))
    op.drop_column('reference', 'url')
    op.add_column('license', sa.Column('web', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('license', sa.Column('title', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'license', type_='unique')
    op.create_index('title', 'license', ['title'], unique=True)
    op.drop_column('license', 'url')
    op.drop_column('license', 'name')
    op.alter_column('dataset', 'deleted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('dataset', 'data_quality',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
